meta_product_name: "SIMYA"
meta_title: "SIMYA - Facilitez-vous la garde alternée"
meta_description: "Parents séparés? Rendez la garde de vos enfants plus facile!
Simya vous permet de mieux vous organisez pour le bonheur de vos enfants"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@simya_twitter_account"   # required for Twitter Cards
